### ISSUE TITLE
Feature Idea tracking issue

### ISSUE THREAD

**Issue by fkearney8** [fkearney8/151Challenge#2]
This issue is to track feature ideas/needs where we can all comment.
- Page to add entries / edit your entries
- Page to view all entries
- Integration with GroupMe https://dev.groupme.com/docs/v3
  *\* Post people's entry feed to GroupMe, allows easy commenting on it.
- Progress page with cool visualizations
  *\* How far each person (or each of top 10) is for each exercise.
  *\* What kind of visualization stuff in HTML is out there? Haven't looked, no experience with this.
- Wall of Fame page - pictures of people drinking their 151 shot (if any ;)

Put more ideas below and I'll edit this top entry if it's going to happen.

**Comment by fkearney8** [comment]
We need a logo. Maybe a random logo generator that scans google images for "Fitness clip art" and randomly places a few Bacardi logos on it.

**Comment by srutisha** [comment]
Back links.

**Comment by fkearney8** [comment]
Bryan, were still going to work on a menu for the left side? I can put that together if not.
