### ISSUE TITLE
Friendlier URL

### ISSUE THREAD

**Issue by fkearney8** [fkearney8/151Challenge#21]
Pogo may have a Cname we can use, or AWS settings may allow it.

**Comment by fkearney8** [comment]
Pogo made http://151.lidaka.us/
We should change the URI on the GroupMe and maybe other places?

**Comment by alidaka** [comment]
I updated the GroupMe title...is there anywhere else?

I think that is a reasonable (at least, IMO more readable/memorable...) URL, short of buying a fresh domain!

**Comment by fkearney8** [comment]
Yeah that seems fine to me - happy to leverage your domain for the site.
I'll push the code in a second, I forget to do it after the update for the
new year. Take a look in about 10.

Frank

**Comment by alidaka** [comment]
Sweet, thanks!

**Comment by fkearney8** [comment]
It's updated if you're looking for it now.
